#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub [-N jobname] myjobname.qsub projectname'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
#
# Set SCC project
#$ -P tcwlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours (6 should work)
#$ -l h_rt=6:00:00

# Combine output and error files into a single file
#$ -j y

#  Name the log directory where to redirect standard output and error
#$ -o logs/cellRanger.log # make sure qlog/ exists and is in the working directory, otherwise give the full path.


#  request enough memory:
# -l mem_per_core=8G

# Specify computing resources
# can be omp, 
#$ -pe omp 16

source /usr3/graduate/akg/miniconda3/bin/activate /usr3/graduate/akg/miniconda3/envs/cellranger-7.2.0

module load cellranger

# Set paths to your ref genome and annotation GTF file
REFERENCE=/projectnb/tcwlab/RawData/Genome/hg38/Homo_sapiens_assembly38.fasta
GTF=/projectnb/tcwlab/RawData/Genome/hg38/gencode.v26.annotation.gtf

# parent directory containing the 24 sample directories
DATA_PARENT_DIR=/projectnb/tcwlab/LabMember/akg/APOE_Jorganoid_project/ref_data/APOE_Jorganoid/data/data/230804_A00220_0594_BHG5H3DSX7

# output directory for CellRanger results
OUTPUT_DIR=/projectnb/tcwlab/LabMember/akg/APOE_Jorganoid_project/outputs/cellRanger

# iterate over each sample directory and run CellRanger count
# list all fastq R1 files in the directory
fastq_r1_files=("$FASTQ_DIR"/*_R1_001.fastq.gz)

# iterate over each R1 fastq file and run CellRanger count 
for fastq_r1_file in "${fastq_r1_files[@]}"; do
    sample_name=$(basename "$fastq_r1_file" | cut -d "_" -f 1)

    echo "Processing sample: $sample_name"

    # corresponding R2 fastq file
    fastq_r2_file="$FASTQ_DIR/${sample_name}_R2_001.fastq.gz"

    # CellRanger count command
    cellranger count \
        --id="$sample_name" \
        --transcriptome="$REFERENCE" \
        --fastqs="$fastq_r1_file","$fastq_r2_file" \
        --sample="$sample_name" \
        --localcores=16 \
        --localmem=64

    # mv result to the output directory
    mv "$sample_name" "$OUTPUT_DIR"
done

echo "cellRanger count completed for all samples."
