#!/bin/bash -l

# Set SCC project
#$ -P tcwlab

# Specify hard time limit for the job. 
#$ -l h_rt=8:00:00

# Combine output and error files into a single file
#$ -j y 

# Name the log directory where to redirect standard output and error
#$ -o /projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/logs/01-Simpleaf_Outputs/21_S6.log

# Request enough memory:
#$ -l mem_per_core=8G

# Specify number of cores
#$ -pe omp 32
echo "running micromamba activate simpleaf . . ."

# Load Conda environment
micromamba activate simpleaf2


echo "running export ALEVIN_FRY_HOME= . . . "
# Set environment variable
export ALEVIN_FRY_HOME="/usr3/graduate/akg/micromamba/envs/simpleaf2"

# Set ulimit
ulimit -n 4096

echo "running simpleaf set-paths . . ."
#Run commands
simpleaf set-paths

echo 'simpleaf inspect: . . .'
simpleaf inspect

echo "running: simplead quant . . ."
# Dual Index kit from 10x Genomics (3 prime)
simpleaf quant \
  --reads1 '/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L001_R1_001.fastq.gz,/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L002_R1_001.fastq.gz,/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L003_R1_001.fastq.gz'\
  --reads2 '/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L001_R2_001.fastq.gz,/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L002_R2_001.fastq.gz,/projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/RawData/organoid/21_S6_L003_R2_001.fastq.gz'\
  --threads 28\
  --index /projectnb/tcwlab/RefData/10XGenomics/refdata-gex-GRCh38-2020-A/simpleaf_91bp/index\
  --chemistry 10xv3\
  --resolution cr-like --unfiltered-pl --expected-ori fw\
  --t2g-map /projectnb/tcwlab/RefData/10XGenomics/refdata-gex-GRCh38-2020-A/simpleaf_91bp/index/t2g_3col.tsv\
  --output /projectnb/tcwlab/LabMember/akg/projects/APOE_Organoid/outputs/01-Simpleaf_Outputs/21_S6/
